import './globals.css'
import Link from 'next/link'
import { Suspense } from 'react'
import Loading from '@/app/loading.js'
import { Header } from "./header"



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// 默认写的是{children}，但是我们写成props的时候要把{}去掉
export default function RootLayout(props) {
  
  let pages = ['Profile', 'About', 'Contact']
  return (
    <html lang="en">
      <body>
        <Header/>
        <div>你好世界</div>
      </body>
    </html>
  )
}
